# Generated by Django 3.2.7 on 2021-11-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0002_accountadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountAdmin',
        ),
    ]
