# Generated by Django 3.2.7 on 2022-01-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediumBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_headline', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('m_image', models.ImageField(blank=True, upload_to='photos/medium_banners')),
                ('m_tag', models.CharField(max_length=30)),
                ('m_btn_text', models.CharField(max_length=15)),
            ],
        ),
    ]
