# Generated by Django 3.2.7 on 2021-12-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmallBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_banner_sub_heading', models.CharField(max_length=50, null=True)),
                ('small_banner_heading', models.CharField(max_length=50, unique=True)),
                ('small_banner_btn_heading', models.CharField(max_length=30, null=True)),
                ('small_banner_btn_url', models.CharField(max_length=50, null=True)),
                ('small_banner_img', models.ImageField(blank=True, upload_to='photos/small_banners')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'small_banner_heading',
                'verbose_name_plural': 'small_banners_headings',
            },
        ),
    ]
