# Generated by Django 3.2.7 on 2021-11-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_smallbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallbanner',
            name='content_details_br',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
