# Generated by Django 3.2.7 on 2021-12-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_smallbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmallBanner',
        ),
    ]
