# Generated by Django 3.2.7 on 2022-01-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220101_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images_hover',
            new_name='image_hover',
        ),
    ]
