# Generated by Django 3.2.7 on 2022-01-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_image_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_hover',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
