# Generated by Django 3.2.7 on 2022-01-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_image_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_class',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
