# Generated by Django 3.2.7 on 2022-01-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220101_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag_class',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
