# Generated by Django 3.2.7 on 2022-01-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_tag_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image_m', models.ImageField(blank=True, upload_to='photos/medium_banners')),
                ('product_m_tag', models.CharField(max_length=30)),
                ('product_m_headline', models.CharField(max_length=50)),
                ('product_btn_text', models.CharField(max_length=15)),
            ],
        ),
    ]
