# Generated by Django 3.2.7 on 2022-01-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_mediumbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumbanner',
            name='product_m_headline',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
