# Generated by Django 3.2.7 on 2022-01-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_mediumbanner_product_m_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediumbanner',
            old_name='product_btn_text',
            new_name='m_btn_text',
        ),
        migrations.RenameField(
            model_name='mediumbanner',
            old_name='product_m_headline',
            new_name='m_headline',
        ),
        migrations.RenameField(
            model_name='mediumbanner',
            old_name='image_m',
            new_name='m_image',
        ),
        migrations.RenameField(
            model_name='mediumbanner',
            old_name='product_m_tag',
            new_name='m_tag',
        ),
    ]
