# Generated by Django 3.2.7 on 2022-01-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220101_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediumBanner',
        ),
    ]
